# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eyepetizer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eyepetizer
  pod 'ReactiveObjC'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'YYWebImage'

  target 'EyepetizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EyepetizerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
